### ISSUE TITLE
Unexpected failure: invalid expression for `if: ${{ failure() }}`

### ISSUE THREAD

**Issue by JamesMGreene** [cschleiden/actions-linter#37]
When using this linter, we are seeing unexpected failures of `Invalid expression` when using an `if: ${{ failure() }}` expression on job steps.

![image](https://user-images.githubusercontent.com/417751/104548309-24a45f80-55f6-11eb-8ba3-6ea85f81209d.png)

According to the Actions docs, this is the correct expression to use for checking if the job has failed prior to arriving at a given step:

- https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idif
- https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions#job-status-check-functions

**Comment by cschleiden** [comment]
Hah.. guess I have my answer to this question now:
![image](https://user-images.githubusercontent.com/2201819/104819418-38141e00-57e2-11eb-8bcb-fc1c1e3892a6.png)
