### ISSUE TITLE
Unknown context access: fails to detect existence of some secrets

### ISSUE THREAD

**Issue by JamesMGreene** [cschleiden/actions-linter#38]
While running this over our workflows, it seems to detect some secrets as valid but fails to detect others. 🤔 

![image](https://user-images.githubusercontent.com/417751/104548808-2f132900-55f7-11eb-9c8e-91de7db68821.png)

This secret definitely exists within the repository:

![image](https://user-images.githubusercontent.com/417751/104548885-5964e680-55f7-11eb-8670-458a3aa2f012.png)

**Comment by cschleiden** [comment]
Yeah, as stated in the README, the underlying parser is able to make API calls to fetch the list of secrets and validate against those, but the default `GITHUB_TOKEN` doesn't have enough permissions for all API calls and that functionality is currently all or nothing. Therefore the linter does not make use of that dynamic feature.

For now, I'll allow all secrets to be access from the linter.
