### ISSUE TITLE
Failed check annotation attributed to incorrect line for unexpected event type

### ISSUE THREAD

**Issue by JamesMGreene** [cschleiden/actions-linter#39]
Failed check annotation attributed to incorrect line for unexpected event type

![image](https://user-images.githubusercontent.com/417751/104549069-b6609c80-55f7-11eb-9b29-4a7a6c7f66a9.png)

The failure was attributed to the first event specified (line 4) rather than to the event it is unhappy about (line 9):

![image](https://user-images.githubusercontent.com/417751/104549157-e6a83b00-55f7-11eb-9392-3557015cf034.png)

**Comment by cschleiden** [comment]
Oh, that's a good one. Turns out I always used the parent mapping node to determine the location.
