### ISSUE TITLE
Blocker: Add support for the new `concurrency` key

### ISSUE THREAD

**Issue by JamesMGreene** [cschleiden/actions-linter#78]
Need to add support for the new `concurrency` key:
- https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
- https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#concurrency

![image](https://user-images.githubusercontent.com/417751/121914313-c4762e80-ccf7-11eb-9952-3e1e3632beb2.png)

Thank you in advance! 🙏🏻 🙇🏻‍♂️

**Comment by JamesMGreene** [comment]
This has been [addressed upstream in `github-actions-parser`](https://github.com/cschleiden/github-actions-parser/commit/26e247578aceb5667dda7670ef72295e7a2e88f2#diff-25a6634263c1b1f6fc4697a04e2b9904ea4b042a89af59dc93ec1f5d44848a26), now it just needs to be released in this Action. 🙏🏻 🙇🏻‍♂️

**Comment by cschleiden** [comment]
Consumed the updated parser.

**Comment by JamesMGreene** [comment]
Awesome! ✨ 

Thank you! ❤️
